### ISSUE TITLE
antd theme 颜色生成

### ISSUE THREAD

**Issue by lin-123** [lin-123/blog#10]
# antd 颜色算法

1. 输入原始色， 调用 colorPalette 获得最终色
    ```less
    // --- 主题色
    @primary-color: #002CE9;
    @primary-1: color(~`colorPalette('@{primary-color}', 1) `); // replace tint(@primary-color, 90%)
    @primary-2: color(~`colorPalette('@{primary-color}', 2) `); // replace tint(@primary-color, 80%)
    @primary-3: color(~`colorPalette('@{primary-color}', 3) `); // unused
    @primary-4: color(~`colorPalette('@{primary-color}', 4) `); // unused
    @primary-5: color(~`colorPalette('@{primary-color}', 5) `); // unused
    @primary-6: @primary-color; // color used to control the text color of active buttons, don't use, use @primary-color
    @primary-7: color(~`colorPalette('@{primary-color}', 7) `); // replace shade(@primary-color, 5%)
    @primary-8: color(~`colorPalette('@{primary-color}', 8) `); // unused
    @primary-9: color(~`colorPalette('@{primary-color}', 9) `); // unused
    @primary-10: color(~`colorPalette('@{primary-color}', 10) `); // unused
    ```

2. colorPalette
    ```less
    /* stylelint-disable no-duplicate-selectors */
    @import "bezierEasing";
    @import "tinyColor";

    // We create a very complex algorithm which take the place of original tint/shade color system
    // to make sure no one can understand it 👻
    // and create an entire color palette magicly by inputing just a single primary color.
    // We are using bezier-curve easing function and some color manipulations like tint/shade/darken/spin
    .colorPaletteMixin() {
    @functions: ~`(function() {
      var hueStep = 2;
      var saturationStep = 16;
      var saturationStep2 = 5;
      var brightnessStep1 = 5;
      var brightnessStep2 = 15;
      var lightColorCount = 5;
      var darkColorCount = 4;

      var getHue = function(hsv, i, isLight) {
        var hue;
        if (hsv.h >= 60 && hsv.h <= 240) {
          hue = isLight ? hsv.h - hueStep * i : hsv.h + hueStep * i;
        } else {
          hue = isLight ? hsv.h + hueStep * i : hsv.h - hueStep * i;
        }
        if (hue < 0) {
          hue += 360;
        } else if (hue >= 360) {
          hue -= 360;
        }
        return Math.round(hue);
      };
      var getSaturation = function(hsv, i, isLight) {
        var saturation;
        if (isLight) {
          saturation = Math.round(hsv.s * 100) - saturationStep * i;
        } else if (i === darkColorCount) {
          saturation = Math.round(hsv.s * 100) + saturationStep;
        } else {
          saturation = Math.round(hsv.s * 100) + saturationStep2 * i;
        }
        if (saturation > 100) {
          saturation = 100;
        }
        if (isLight && i === lightColorCount && saturation > 10) {
          saturation = 10;
        }
        if (saturation < 6) {
          saturation = 6;
        }
        return Math.round(saturation);
      };
      var getValue = function(hsv, i, isLight) {
        if (isLight) {
          return Math.round(hsv.v * 100) + brightnessStep1 * i;
        }
        return Math.round(hsv.v * 100) - brightnessStep2 * i;
      };

      this.colorPalette = function(color, index) {
        var isLight = index <= 6;
        var hsv = tinycolor(color).toHsv();
        var i = isLight ? lightColorCount + 1 - index : index - lightColorCount - 1;
        return tinycolor({
          h: getHue(hsv, i, isLight),
          s: getSaturation(hsv, i, isLight),
          v: getValue(hsv, i, isLight),
        }).toHexString();
      };
    })()`;
    }
    // It is hacky way to make this function will be compiled preferentially by less
    // resolve error: `ReferenceError: colorPalette is not defined`
    // https://github.com/ant-design/ant-motion/issues/44
    .colorPaletteMixin();
    ```
